#!/bin/bash

# Return information on battery
# Copyright 2021 obtusedev

set -e

HELP="Usage: $0 [option]\n
-h, --help     print help\n
-V, --version  print version"

VERSION='battery version 1.0'

battery_info_verbose() {
  battery_path=$(upower -e | sed -n '2p')
  echo "Battery file located at: $battery_path"
  upower -i "$battery_path"
}

if [ $# -eq 0 ]; then
  battery_info_verbose
elif [ $# -eq 1 ]; then
  if [ $1 == '-V' ] || [ $1 == '--version' ]; then
    echo $VERSION
  elif [ $1 == '-h' ] || [ $1 == '--help' ]; then
    echo -e $HELP
  else
    echo "Invalid flag $1"
  fi
else
  echo 'Something went wrong'
fi