#!/bin/bash

# Return information on battery
# Copyright 2021 obtusedev

set -e

HELP="Usage: $0 [option]\n
-h, --help     print help\n
-V, --version  print version"

VERSION="battery version 1.0"

battery_info_verbose() {
  battery_path=$(upower -e | sed -n '2p')
  echo "Battery file located at: $battery_path"
}
