#!/bin/bash

# Return information on battery
# Copyright 2021 obtusedev

set -e

HELP="Usage: $0 [option]\n
-h, --help     print help\n
-V, --version  print version\n
-v, --verbose  verbose ouput"

VERSION='battery version 1.0'

declare -A battery
battery[path]=$(upower -e | sed -n '2p')
battery[output]=$(upower -i "${battery[path]}")
battery[state]=$(${battery[output]} | awk '/state/ {print $2}')
battery[warning-level]=$(${battery[output]} | awk '/warning-level/ {print $2}')
battery[percentage]=$(${battery[output]} | awk '/percentage/ {print $2}')
battery[capacity]=$(${battery[output]} | awk '/capacity/ {print $2}')
battery[time-to-empty]=''

battery_info_verbose() {
  echo "Battery file located at: ${battery[path]}"
  ${battery[ouput]}
}

battery_info() {
  echo "battery state: ${battery[state]}"
  echo "battery warning: ${battery[warning-level]}"
  echo "battery percentage: ${battery[percentage]}"
  echo "battery capacity: ${battery[capacity]}"
  if [ ${battery[state]} == 'discharging']; then
    echo "battery time to empty: ${battery[time-to-empty]}"
  fi
}

if [ $# -eq 0 ]; then
  battery_info
elif [ $# -eq 1 ]; then
  if [ "$1" == '-V' ] || [ "$1" == '--version' ]; then
    echo "$VERSION"
  elif [ "$1" == '-h' ] || [ "$1" == '--help' ]; then
    echo -e "$HELP"
  elif [ "$1" == '-v' ] || [ "$1" == '--verbose' ]; then
    battery_info_verbose
  else
    echo "Invalid flag $1"
  fi
else
  echo 'Something went wrong'
fi